"use client";

import { AlertTriangle, FileText, Loader2, Rocket } from "lucide-react";
import { type FormEvent, useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const STAGE_OPTIONS = [
  { value: "", label: "Select stage (optional)" },
  { value: "pre-seed", label: "Pre-Seed" },
  { value: "seed", label: "Seed" },
  { value: "series-a", label: "Series A" },
  { value: "series-b", label: "Series B" },
  { value: "series-c", label: "Series C" },
];

const LOADING_STEPS = [
  "Researching market...",
  "Analyzing competitors...",
  "Generating pitch...",
];

interface PitchResult {
  idea: string;
  sector: string | null;
  stage: string | null;
  pitchDeck: string;
  signalCount: number;
}

function PitchDeckDisplay({ pitchDeck }: { pitchDeck: string }) {
  return (
    <div className="glass gradient-border rounded-xl p-5">
      <div className="flex items-center gap-2 mb-4">
        <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-orange-500 to-red-600">
          <FileText className="h-4 w-4 text-white" />
        </div>
        <div>
          <h3 className="text-sm font-bold">Your Pitch Deck</h3>
          <p className="text-[10px] text-muted-foreground">
            10-slide outline generated by AI with live market data
          </p>
        </div>
      </div>
      <div className="text-[12px] leading-relaxed text-foreground/80 [&_p]:mb-2 [&_p:last-child]:mb-0 [&_ul]:mb-2 [&_ul]:list-disc [&_ul]:pl-4 [&_ol]:mb-2 [&_ol]:list-decimal [&_ol]:pl-4 [&_li]:mb-0.5 [&_h1]:text-sm [&_h1]:font-bold [&_h1]:mb-1 [&_h2]:text-[13px] [&_h2]:font-semibold [&_h2]:mt-3 [&_h2]:mb-1 [&_h3]:text-[12px] [&_h3]:font-semibold [&_h3]:mb-1 [&_strong]:font-semibold [&_strong]:text-foreground [&_code]:rounded [&_code]:bg-white/10 [&_code]:px-1 [&_code]:text-[11px] [&_blockquote]:border-l-2 [&_blockquote]:border-white/20 [&_blockquote]:pl-3 [&_blockquote]:italic [&_blockquote]:text-foreground/70 [&_hr]:my-2 [&_hr]:border-white/10">
        <ReactMarkdown remarkPlugins={[remarkGfm]}>
          {pitchDeck}
        </ReactMarkdown>
      </div>
    </div>
  );
}

export function PitchGenerator() {
  const [idea, setIdea] = useState("");
  const [sector, setSector] = useState("");
  const [stage, setStage] = useState("");
  const [result, setResult] = useState<PitchResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [loadingStep, setLoadingStep] = useState(0);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async (e: FormEvent) => {
    e.preventDefault();
    if (!idea.trim() || isLoading) return;

    setIsLoading(true);
    setError(null);
    setResult(null);
    setLoadingStep(0);

    // Cycle through loading steps for UX feedback
    const stepInterval = setInterval(() => {
      setLoadingStep((prev) => (prev + 1) % LOADING_STEPS.length);
    }, 2000);

    try {
      const res = await fetch("/api/pitch", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          idea: idea.trim(),
          sector: sector.trim() || undefined,
          stage: stage || undefined,
        }),
      });

      if (!res.ok) {
        const errText = await res.text();
        let errMsg: string;
        try { errMsg = JSON.parse(errText).error ?? errText; } catch { errMsg = errText; }
        throw new Error(errMsg.slice(0, 200));
      }

      const json = await res.json();
      setResult(json.data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong");
    } finally {
      clearInterval(stepInterval);
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-5">
      {/* Input Section */}
      <div className="glass gradient-border rounded-xl p-5">
        <div className="flex items-center gap-2 mb-4">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-orange-500 to-red-600">
            <Rocket className="h-4 w-4 text-white" />
          </div>
          <div>
            <h2 className="text-sm font-bold">Pitch Deck Generator</h2>
            <p className="text-[10px] text-muted-foreground">
              Describe your startup idea — get a full 10-slide pitch deck with
              live market data in seconds
            </p>
          </div>
        </div>

        <form onSubmit={handleGenerate} className="space-y-3">
          <textarea
            value={idea}
            onChange={(e) => setIdea(e.target.value)}
            placeholder="e.g. An AI-powered tool that helps small businesses automate their compliance reporting..."
            rows={3}
            className="w-full rounded-lg border border-white/10 bg-white/[0.03] px-4 py-3 text-sm text-foreground placeholder:text-muted-foreground focus:border-orange-500/30 focus:outline-none resize-none"
          />

          <div className="flex gap-3">
            <input
              type="text"
              value={sector}
              onChange={(e) => setSector(e.target.value)}
              placeholder="Sector (e.g. FinTech, HealthTech)"
              className="flex-1 h-9 rounded-lg border border-white/10 bg-white/[0.03] px-3 text-sm text-foreground placeholder:text-muted-foreground focus:border-orange-500/30 focus:outline-none"
            />
            <select
              value={stage}
              onChange={(e) => setStage(e.target.value)}
              className="h-9 rounded-lg border border-white/10 bg-white/[0.03] px-3 text-sm text-foreground focus:border-orange-500/30 focus:outline-none"
            >
              {STAGE_OPTIONS.map((opt) => (
                <option key={opt.value} value={opt.value}>
                  {opt.label}
                </option>
              ))}
            </select>
          </div>

          <button
            type="submit"
            disabled={!idea.trim() || isLoading}
            className="flex h-10 w-full items-center justify-center gap-2 rounded-lg bg-gradient-to-r from-orange-500 to-red-600 px-5 text-sm font-medium text-white transition-opacity disabled:opacity-40"
          >
            {isLoading ? (
              <>
                <Loader2 className="h-4 w-4 animate-spin" />
                {LOADING_STEPS[loadingStep]}
              </>
            ) : (
              <>
                <Rocket className="h-4 w-4" />
                Generate Pitch Deck
              </>
            )}
          </button>
        </form>

        {isLoading && (
          <div className="mt-4 space-y-2">
            <div className="flex items-center gap-2 text-[11px] text-muted-foreground animate-pulse">
              <Loader2 className="h-3 w-3 animate-spin" />
              {LOADING_STEPS[loadingStep]}
            </div>
            <div className="h-1 w-full overflow-hidden rounded-full bg-white/5">
              <div className="h-full w-2/3 animate-shimmer rounded-full bg-orange-500/30" />
            </div>
          </div>
        )}

        {error && (
          <div className="mt-3 flex items-center gap-2 rounded-lg bg-red-500/10 px-3 py-2 text-[11px] text-red-400">
            <AlertTriangle className="h-3.5 w-3.5" />
            {error}
          </div>
        )}
      </div>

      {/* Results Section */}
      {result && (
        <div className="space-y-4 animate-fade-in-up">
          {/* Meta info */}
          <div className="glass gradient-border rounded-xl p-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Rocket className="h-4 w-4 text-orange-400" />
                <span className="text-sm font-semibold">
                  {result.idea.length > 60
                    ? result.idea.slice(0, 60) + "..."
                    : result.idea}
                </span>
              </div>
              <div className="flex items-center gap-3 text-[10px] text-muted-foreground">
                {result.sector && (
                  <span className="rounded-full bg-orange-500/10 px-2 py-0.5 text-orange-400">
                    {result.sector}
                  </span>
                )}
                {result.stage && (
                  <span className="rounded-full bg-red-500/10 px-2 py-0.5 text-red-400 capitalize">
                    {result.stage}
                  </span>
                )}
                <span>{result.signalCount} market signals</span>
              </div>
            </div>
          </div>

          {/* Pitch deck content */}
          <PitchDeckDisplay pitchDeck={result.pitchDeck} />
        </div>
      )}
    </div>
  );
}
